[package]
name = "audit-local"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
name = "audit_local"
path = "src/lib.rs"

[[bin]]
name = "audit-local"
path = "src/main.rs"

[dependencies]
aws_net_hound_core = { path = "../core", package = "core" }
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_norway = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
