[package]
name = "audit-local"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
name = "audit_local"
path = "src/lib.rs"

[[bin]]
name = "audit-local"
path = "src/main.rs"

[dependencies]
aws_net_hound_core = { path = "../core", package = "core" }
aws-sdk-ec2 = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
neo4rs = { workspace = true }
serde = { workspace = true }
serde_norway = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
aws-sdk-ec2 = { workspace = true, features = ["test-util"] }
aws-smithy-mocks = { workspace = true }
pretty_assertions = { workspace = true }
