[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
neo4rs = { workspace = true }
serde = { workspace = true }
serde_norway = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
testcontainers = { workspace = true }
